### ISSUE TITLE
Support pre_commands in .drone.yml

### ISSUE THREAD

**Issue by davidhiendl** [davidhiendl/drone-gitea-extensions#1]
Support pre_commands in .drone.yml with same syntax as commands and prepend pre_commands to commands with convert plugin.

Example:
```yaml
kind: pipeline
name: default

steps:
  - name: test
    image: alpine
    pre_commands:
    - echo "abc"
    commands:
    - echo "bcd"
```

And transform it into:
Example:
```yaml
kind: pipeline
name: default

steps:
  - name: test
    image: alpine
    commands:
    - echo "abc"
    - echo "bcd"
```
